name: Deploy

on:
  push:
    tags:
     - '*'

permissions:
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4

     - name: Extract release version
       run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

     - name: Login to ghcr.io
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Setup Buildx
       uses: docker/setup-buildx-action@v3

     - name: Build & push
       uses: docker/build-push-action@v5
       with:
         push: true
         tags: ghcr.io/${{ github.repository }}:latest , ghcr.io/${{ github.repository}}:${{ env.RELEASE_VERSION }}

     - name: Notify Watchtower
       uses: fjogeleit/http-request-action@v1
       with:
         url: ${{ secrets.WATCHTOWER_URL }}
         bearerToken: ${{ secrets.WATCHTOWER_BEARER_TOKEN }}